# Generated by Django 6.0.5 on 2026-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='Black', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=20),
        ),
    ]
